version: "3"
services:
  watchtower:
    image: v2tec/watchtower
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    restart: always
