version: "3.7"
services:
  yts_bot:
    image: hibare/yts_bot
    container_name: yts_bot
    hostname: yts_bot
    restart: always
    environment:
      - SLACK_ENDPOINT=<your value>
      - INTERVAL=12 #Optinal, default=12 hours
    volumes:
      - yts_movie_list:/app/yts_movie_list.txt
volumes:
  yts_movie_list:
