version: "3.7"
services:
  tasker:
    image: strm/tasker
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      configuration: |
        logging:
            level:
                ROOT: WARN
                org.springframework.web: WARN
                sh.strm: DEBUG
        schedule:
            - every: 6 hours
              task: yts_bot
        tasks:
            docker:
                - name: yts_bot
                  image: python:3
                  script-strict: true
                  script:
                    - cd /app
                    - pip install -r requirements.txt
                    - python3 yts_bot.py
                  volumes:
                    - <absolute path to src>/src:/app
